services:
  dev:
    privileged: true
    container_name: dev
    image: ghcr.io/benlocal/docker-dev-container:noble
    ports:
      - "2222:22"
    restart: always
    environment:
      - ROOT_PWD=1234
